version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app:/app
    ports:
      - 8000:8000
    env_file:
      - app/app/.env
    depends_on:
      - db
  db:
    image: "postgres" # use latest official postgres version
    env_file:
      - app/app/.env # configure postgres

res_data: